const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
const GET_WALLETS = 'GET_WALLETS';
const SET_WALLETS = 'SET_WALLETS';
const GET_RATES = 'GET_RATES';
const SET_RATES = 'SET_RATES';
const ADD_WALLET = 'ADD_WALLET';
const SAVE_RATE = 'SAVE_RATE';

export default {
  INCREMENT,
  DECREMENT,
  INCREMENT_ASYNC,
  GET_WALLETS,
  SET_WALLETS,
  GET_RATES,
  SET_RATES,
  ADD_WALLET,
  SAVE_RATE
};